architecture: L2MU
num_inputs: 12
num_outputs: 7
params:
  batch_size: 64
  beta_spk_h: 0.45
  beta_spk_m: 0.2
  beta_spk_output: 0.6000000000000001
  beta_spk_u: 0.8
  hidden_size: 120.0
  lr: 0.0014500000000000001
  memory_size: 70.0
  order: 7.0
  theta: 10.0
  threshold_spk_h: 0.65
  threshold_spk_m: 0.4
  threshold_spk_output: 0.15000000000000002
  threshold_spk_u: 0.2
